workflows:

  flutter-ios-simulator:

    name: Flutter iOS Simulator

    environment:

      flutter: 3.35.2

      xcode: 16.2

    scripts:

      - flutter build ios --simulator  # --flavor is optional

    artifacts:

      - build/ios/iphonesimulator/Runner.app